### PR TITLE
add RSA_NO_PADDING support compatible with bouncycastle

### PR DESCRIPTION
**Pull request by bombworm**
new NodeRSA(keyBuffer, 'nopadding-private', {encryptionScheme: 'nopadding'});

### CODE REVIEW

**Comment by rzcoder** [comment]
So, first of all tests failed

**Comment by bombworm** [comment]
I'll check it, I think I need patch it for old version node

**Comment by bombworm** [comment]
Test error was caused by lastIndexOf method of Buffer not exist in old version node

**Comment by rzcoder** [comment]
Ok, then

1. Why you add `formats/nopadding.js` if it just a copy of `formats/pkcs1.js`?
2. Why you make full copy of `schemes/pkcs1.js` in `schemes/nopadding.js?` `nopadding.js` should extend `pkcs1.js` Also, I think better to do nopadding option for pkcs1 than new equal scheme.
3. You didn't update `encryptEngines/io.js` properly, as well as `encryptEngines/node12.js` for use nopadding scheme.
4. You don't make changes in tests.

**Comment by bombworm** [comment]
Er.... My project was just need decrypt rsa data which encrypted by JAVA package org.bouncycastle. I only have the encrypted data and private key, and I only concern about the decrypted data, so I don't make the encrypt method correctly.
I think you are right, It's better be an option with `pkcs1`.
I need more time to make it better but I'm troubling with my project.
I'll rewrite later.

**Pull request closed without merging**
